import React from 'react';
import { motion } from 'framer-motion';
import { 
  ShieldAlert, Lock, Database, EyeOff, UserCheck, 
  HelpCircle, Scale, GraduationCap, HeartPulse 
} from 'lucide-react';
import { useTheme } from '../context/ThemeContext';

const PrivacyPolicy = () => {
  const { theme } = useTheme();
  const isLight = theme === 'light';

  const sections = [
    {
      icon: <GraduationCap className="h-5 w-5 text-med-primary" />,
      title: "1. Academic Project Scope",
      content: "This software is developed strictly as a college final-year project for academic demonstration and research purposes. It represents a theoretical application of machine learning classifiers to symptom-checker datasets. It is NOT certified as a medical device by any health authority."
    },
    {
      icon: <HeartPulse className="h-5 w-5 text-red-500" />,
      title: "2. Medical Consultation Disclaimer",
      content: "Always consult a licensed medical professional, doctor, or emergency clinic for any actual health symptoms, diagnosis, or treatment. Never disregard professional clinical advice or delay seeking it because of diagnostic feedback generated by this platform. The model accuracy scores are simulation benchmarks and should not guide real-life clinical choices."
    },
    {
      icon: <Lock className="h-5 w-5 text-blue-500" />,
      title: "3. Account Security & Hashing",
      content: "User authentication credentials are encrypted using secure bcrypt salt hashing inside the database layer. JWT (JSON Web Tokens) are utilized to manage stateful sessions securely. We recommend using unique mock passwords for this educational workspace."
    },
    {
      icon: <Database className="h-5 w-5 text-emerald-500" />,
      title: "4. Diagnostic Telemetry Logs",
      content: "Symptom logs and predicted outcomes are stored locally inside the project's SQL database solely to populate your personal 'Consultations' history tab. These logs can be cleared at any time by requesting account deletion under profile settings, or by dropping the local SQLite db."
    },
    {
      icon: <EyeOff className="h-5 w-5 text-purple-500" />,
      title: "5. Zero Data Commercialization",
      content: "This project operates on a non-commercial foundation. No cookie trackers, advertising scripts, or profiling cookies are deployed. We never sell, lease, or distribute entered health telemetry strings to pharmaceutical firms, insurance brokers, or external entities."
    },
    {
      icon: <Scale className="h-5 w-5 text-yellow-500" />,
      title: "6. Terms & Policy Alterations",
      content: "As a static academic release, these guidelines are permanent. Any updates to the underlying classifier algorithms will be noted in the 'About Project' telemetry panel rather than altering user data permissions."
    }
  ];

  return (
    <div className={`max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8 text-left space-y-10 relative transition-colors duration-300 ${
      isLight ? 'text-med-text' : 'text-gray-300'
    }`}>
      {/* Background Glowing Orbs */}
      <div className={`absolute top-20 left-[10%] w-80 h-80 rounded-full blur-[100px] pointer-events-none -z-10 opacity-70 ${
        isLight ? 'bg-med-secondary' : 'bg-primary/10'
      }`} />
      
      {/* Page Title */}
      <div className={`border-b pb-5 ${isLight ? 'border-gray-200' : 'border-white/[0.06]'}`}>
        <motion.h1 
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className={`text-3xl font-extrabold flex items-center gap-3 ${isLight ? 'text-med-text' : 'text-white'}`}
        >
          <div className={`p-2.5 rounded-2xl border shadow-premium-sm ${
            isLight ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-500' : 'bg-emerald-500/10 border-emerald-500/20 text-emerald-500'
          }`}>
            <UserCheck className="h-6 w-6 text-current" />
          </div>
          Privacy Policy & Security
        </motion.h1>
        <p className={`text-xs mt-2.5 max-w-xl leading-relaxed ${isLight ? 'text-med-gray' : 'text-gray-400'}`}>
          Detailed security parameters, user confidentiality declarations, and educational disclaimers regarding the Aegis AI project.
        </p>
      </div>

      {/* College Project Disclaimer banner */}
      <motion.div 
        initial={{ opacity: 0, scale: 0.98 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.4 }}
        className={`border p-6 rounded-3xl flex items-start gap-4 shadow-premium-sm ${
          isLight ? 'bg-amber-50 border-amber-200 text-amber-950' : 'bg-amber-500/[0.05] border border-amber-500/30 text-amber-200'
        }`}
      >
        <ShieldAlert className="h-7 w-7 text-amber-500 shrink-0 mt-0.5" />
        <div className="space-y-1.5 text-xs text-left">
          <h4 className="font-bold text-amber-500 font-poppins text-sm uppercase tracking-wide">Academic Demonstration Agreement</h4>
          <p className={`${isLight ? 'text-gray-700' : 'text-gray-300'} leading-relaxed`}>
            <b>PLEASE READ:</b> By accessing and utilizing Aegis AI, you acknowledge that this is a <b>college project built for educational evaluation</b>. The predictions are generated by basic machine learning models trained on simulated diagnostic vectors and should not be used as clinical diagnostic guidance. For actual health concerns, please consult a certified doctor.
          </p>
        </div>
      </motion.div>

      {/* Policy Sections Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
        {sections.map((section, idx) => (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.05 * idx }}
            key={idx}
            className={`p-6 rounded-3xl flex flex-col gap-3 justify-between hover:shadow-premium-md transition-all duration-300 border ${
              isLight ? 'glass-panel-light border-med-secondary bg-white/70 hover:-translate-y-0.5' : 'glass-panel border-white/[0.06] bg-dark-surface/50 hover:-translate-y-0.5'
            }`}
          >
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-left">
                <div className={`p-1.5 rounded-lg ${isLight ? 'bg-med-secondary text-med-primary' : 'bg-white/5 text-white'}`}>
                  {section.icon}
                </div>
                <h3 className={`text-sm font-bold font-poppins ${isLight ? 'text-med-text' : 'text-white'}`}>
                  {section.title}
                </h3>
              </div>
              <p className={`text-xs leading-relaxed font-inter ${isLight ? 'text-med-gray' : 'text-gray-400'}`}>
                {section.content}
              </p>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Footer support details */}
      <div className={`text-center pt-8 border-t text-[11px] ${isLight ? 'border-gray-200 text-med-gray' : 'border-white/5 text-gray-500'}`}>
        <HelpCircle className="inline h-4 w-4 mr-1 text-gray-400" />
        Have questions regarding the dataset or model files? Review our code repository or contact the project advisory team at your college.
      </div>

    </div>
  );
};

export default PrivacyPolicy;
